=== 2pees/enaml/enaml/workbench/plugin_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Enaml Workbench Plugin Schema",
	"description": "The JSON schema for an Enaml workbench plugin manifest.",
	"type": "object",
	"required": [ "id" ],
	"additionalProperties": false,
	"properties": {
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"class": {
			"type": "string"
		},
		"extensionPoints": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/extensionPoint"
			}
		},
		"extensions": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/extension"
			}
		}
	},
	"definitions": {
		"extensionPoint": {
			"type": "object",
			"required": [ "id" ],
			"additionalProperties": false,
			"properties": {
				"id": {
					"type": "string"
				},
				"name": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"schema": {
					"type": "string"
				},
				"interface": {
					"type": "string"
				}
			}
		},
		"extension": {
			"type": "object",
			"required": [ "id", "point" ],
			"properties": {
				"id": {
					"type": "string"
				},
				"point": {
					"type": "string"
				},
				"name": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"class": {
					"type": "string"
				},
				"rank": {
					"type": "number"
				}
			}
		}
	}
}

=== 2pees/enaml/enaml/studio/plugins/core.json
{
	"id": "enaml.studio.core",
	"name": "Enaml Studio Core",
	"description": "The Enaml studio core plugin.",
	"class": "enaml.studio.core.core_plugin.CorePlugin",
	"extensionPoints": [
		{
			"id": "uriReaders",
			"name": "URI Readers",
			"description": "URI readers are used to load data from a uri.",
			"interface": "enaml.studio.core.uri_reader.URIReader"
		}
	],
	"extensions": [
		{
			"id": "defaultFileReader",
			"point": "enaml.studio.core.uriReaders",
			"name": "Default File Reader",
			"description": "The default uri reader for the local filesystem.",
			"class": "enaml.studio.core.file_reader.FileReader",
			"scheme": "file",
			"rank": -1000
		}
	]
}

=== 2pees/enaml/enaml/studio/plugins/workspace.json
{
	"id": "enaml.studio.workspace",
	"name": "Enaml Studio Workspace",
	"description": "The Enaml Studio workspace plugin.",
	"class": "enaml.studio.workspace.workspace_plugin.WorkspacePlugin",
	"extensionPoints": [
		{
			"id": "configurations",
			"name": "Configurations",
			"description": "The developer provided workspace configurations.",
			"interface": "enaml.studio.workspace.configuration.Configuration",
			"schema": "file://schemas/configuration.json"
		}
	],
	"extensions": [
		{
			"id": "content",
			"point": "enaml.studio.ui.content",
			"name": "Workspace Window Content",
			"description": "The dock area content for the studio window.",
			"class": "enaml.studio.workspace.workspace_content.WorkspaceContent"
		}
	]
}

=== 2pees/enaml/enaml/studio/plugins/ui.json
{
	"id": "enaml.studio.ui",
	"name": "Enaml Studio UI",
	"description": "The Enaml Studio ui plugin.",
	"class": "enaml.studio.ui.ui_plugin.UIPlugin",
	"extensionPoints": [
		{
			"id": "application",
			"name": "Studio Application",
			"description": "The Enaml Application factory.",
			"interface": "enaml.studio.ui.application_factory.ApplicationFactory"
		},
		{
			"id": "window",
			"name": "Studio Window",
			"description": "The primary StudioWindow factory.",
			"interface": "enaml.studio.ui.window_factory.WindowFactory"
		},
		{
			"id": "icon",
			"name": "Window Icon",
			"description": "The icon to use for the window and task bar.",
			"interface": "enaml.studio.ui.icon_provider.IconProvider"
		},
		{
			"id": "title",
			"name": "Window Title",
			"description": "The string to use for the window title bar.",
			"interface": "enaml.studio.ui.title_provider.TitleProvider"
		},
		{
			"id": "menus",
			"name": "Window Menus",
			"description": "The menus to use in the window menu bar.",
			"interface": "enaml.studio.ui.menu_provider.MenuProvider"
		},
		{
			"id": "content",
			"name": "Window Content",
			"description": "The primary content for the studio window.",
			"interface": "enaml.studio.ui.content_provider.ContentProvider"
		}
	],
	"extensions": [
		{
			"id": "defaultApplication",
			"point": "enaml.studio.ui.application",
			"name": "Default Application Factory",
			"description": "The default application factory which creates a QtApplication.",
			"class": "enaml.studio.ui.qt_application_factory.QtApplicationFactory",
			"rank": -1000
		},
		{
			"id": "defaultWindow",
			"point": "enaml.studio.ui.window",
			"name": "Default Window Factory",
			"description": "The default window factory which creates a base StudioWindow.",
			"class": "enaml.studio.ui.studio_window_factory.StudioWindowFactory",
			"rank": -1000
		},
		{
			"id": "defaultTitle",
			"point": "enaml.studio.ui.title",
			"name": "Default Window Title",
			"description": "The default studio window title.",
			"title": "Enaml Studio",
			"rank": -1000
		}
	]
}
