=== 2pees/enaml/enaml/workbench/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Plugin Schema",
	"description": "The JSON Schema for an Enaml plugin manifest.",
	"type": "object",
	"required": ["id"],
	"additionalProperties": false,
	"properties": {
		"id": {
			"type": "string"
		},
		"name": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"class": {
			"type": "string"
		},
		"extension_points": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/extensionPoint"
			}
		},
		"extensions": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/extension"
			}
		}
	},
	"definitions": {
		"extensionPoint": {
			"type": "object",
			"required": ["id"],
			"additionalProperties": false,
			"properties": {
				"id": {
					"type": "string"
				},
				"name": {
					"type": "string"
				},
				"description": {
					"type": "string"
				}
			}
		},
		"extension": {
			"type": "object",
			"required": ["point"],
			"additionalProperties": false,
			"properties": {
				"point": {
					"type": "string"
				},
				"id": {
					"type": "string"
				},
				"name": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"class": {
					"type": "string"
				},
				"configuration": {
					"type": "object"
				}
			}
		}
	}
}

=== 2pees/enaml/enaml/studio/plugins/core_ui.json
{
	"id": "enaml.studio.core.ui",
	"name": "Studio Core UI",
	"description": "The core Enaml Studio UI plugin.",
	"class": "enaml.studio.core_ui_plugin.CoreUIPlugin",
	"extension_points": [
		{
			"id": "title",
			"name": "Studio UI Title",
			"description": "The extension point for the main window title."
		},
		{
			"id": "menubar",
			"name": "Studio UI Menu Bar",
			"description": "The extension point for the main window menu bar."
		},
		{
			"id": "content",
			"name": "Studio UI Central Content",
			"description": "The extension point for main window central widget."
		}
	]
}
